import type { Metadata } from "next";
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
    title: {
        //absolute: "Create Next App", // to ignore template and use this value
        default: "Create Next App", // for this page
        template: "%s | Create Next App", // for other pages (children)
    },
    description: "Generated by create next app",
};

export default function RootLayout({
           children,
       }: Readonly<{children: React.ReactNode;
}>) {
    return (
        <html lang="en">
        <body className={inter.className}>
        <div>
            header
        </div>

        {children}

        <div>
            footer
        </div>
        </body>
        </html>
    );
}
